import { type NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { useState } from "react";

import { api } from "../utils/api";

const SubmitBuild: NextPage = () => {
  const createBuildMutation = api.builds.createBuild.useMutation();

  const [matchUp, setMatchUp] = useState("zvt");
  const [build, setBuildOrder] = useState("");
  const router = useRouter();

  function handleSubmitBuildOrder(e: React.FormEvent) {
    e.preventDefault();

    createBuildMutation
      .mutateAsync({
        matchUp,
        build,
      })
      .then(() => router.push("/builds"))
      .catch((error: unknown) => console.error({ error }));
  }

  return (
    <>
      <Head>
        <title>Submit a build</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center gap-8 bg-gradient-to-b from-[#2e026d] to-[#15162c] text-white">
        <h1>Submit a Build Order</h1>

        <form className="flex flex-col gap-4" onSubmit={handleSubmitBuildOrder}>
          <label htmlFor="match-up-select">Match Up</label>
          <select
            id="match-up-select"
            className="text-black"
            onChange={(e) => setMatchUp(e.target.value)}
            value={matchUp}
            required
          >
            <option value="zvt">ZvT</option>
            <option value="zvp">ZvP</option>
            <option value="zvz">ZvZ</option>

            <option value="pvt">PvT</option>
            <option value="pvp">PvP</option>
            <option value="pvz">PvZ</option>

            <option value="tvt">TvT</option>
            <option value="tvp">TvP</option>
            <option value="tvz">TvZ</option>
          </select>

          <textarea
            required
            className="p-2 text-black"
            value={build}
            onChange={(e) => setBuildOrder(e.target.value)}
          />

          <button className="bg-white p-2 text-black">Submit</button>
        </form>
      </main>
    </>
  );
};

export default SubmitBuild;
